import './globals.css';
import Navbar from '@/Components/Navbar';
import Footer from '@/Components/Footer';
import ShopContextProvider from './Context/Context';
import SearchBar from '@/Components/SearchBar';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "E-Commerce Template",
  description: "Generated by codewithstella",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='px-4 sm:px-[5vw] md:px-[7vw] lg:px-[9vw] '>
          <ShopContextProvider>
            <ToastContainer />
            <Navbar />
            <SearchBar/>
            {children}
            <Footer />
        </ShopContextProvider>
        </div>
        
      </body>
    </html>
  );
}

